# We use MySQL for both development and test because of the following reasons:
#
# - At the time being, schema.rb isn't DB-agnostic anymore (it adds options about used engine, etc.), which makes it difficult to use in different database types (e.g. MySQL for development and SQLite for test), more info see https://github.com/rails/rails/issues/26209
# - Running specs using Selenium (e.g. driver: :chrome) results in an SQLite3::BusyException error when using SQLite

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  database: <%= Rails.application.class.parent_name.underscore %>_development
  username: <%= Rails.application.secrets.database_username %>
  password: <%= Rails.application.secrets.database_password %>
  <<: *default

test:
  database: <%= Rails.application.class.parent_name.underscore %>_test
  username: <%= Rails.application.secrets.database_username %>
  password: <%= Rails.application.secrets.database_password %>
  <<: *default
