relative_roots:
  - app/views
  - app/cells

data:
  # file_system is the default adapter, you can provide a custom class name here:
  adapter: file_system

  # a list of file globs to read from per-locale
  read:
    # default:
    - 'config/locales/%{locale}.yml'
    # to also read from namespaced files, e.g. simple_form.en.yml:
    - 'config/locales/*.%{locale}.yml'
    - 'config/locales/*/%{locale}.yml'
  # a list of {key pattern => file} routes, matched top to bottom

  write:
    # save all devise keys in it's own file (per locale):
    - ['{activerecord,devise,errors,flash,simple_form,validates_timeliness}.*', 'config/locales/\1/%{locale}.yml']
    # default catch-all:
    - 'config/locales/%{locale}.yml' # path is short for ['*', path]

ignore_unused:
  - activerecord.*
  - devise.*
  - errors.*
  - flash.*
  - simple_form.*
  - validates_timeliness.*

ignore_eq_base:
  all:
    - simple_form.required.mark
  de:
    - validates_timeliness.error_value_formats.time

ignore:
  - kaminari.*

yaml:
  write:
    line_width: -1
