relative_roots:
  - app/cells
  - app/helpers
  - app/views

data:
  # file_system is the default adapter, you can provide a custom class name here:
  adapter: file_system

  # a list of file globs to read from per-locale
  read:
    # default:
    - 'config/locales/%{locale}.yml'
    # to also read from namespaced files, e.g. simple_form.en.yml:
    - 'config/locales/*.%{locale}.yml'
    - 'config/locales/*/%{locale}.yml'
  # a list of {key pattern => file} routes, matched top to bottom

  write:
    # save all devise keys in it's own file (per locale):
    - ['{activerecord,actions,devise,enumerize,errors,flash,simple_form,validates_timeliness}.*', 'config/locales/\1/%{locale}.yml']
    # default catch-all:
    - 'config/locales/%{locale}.yml' # path is short for ['*', path]

  yaml:
    write:
      line_width: -1

ignore_unused:
  - activerecord.*
  - actions.*
  - devise.*
  - enumerize.*
  - errors.*
  - flash.*
  - simple_form.*
  - validates_timeliness.*

ignore_eq_base:
  all: # TODO: Maybe we should simply use "*"?
    - simple_form.required.mark
    - activerecord.attributes.*
    - enumerize.*
    - layouts.navigation.home
    - validates_timeliness.error_value_formats.time

ignore:
  - kaminari.*

ignore_untranslated:
  model_names:
    - role
  model_attributes:
    user:
      - encrypted_password
      - reset_password_token
      - reset_password_sent_at
      - remember_created_at
      - unconfirmed_email
      - confirmation_token
      - confirmation_sent_at
      - unlock_token
      - sign_in_count